### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by zhuizhuhaomeng**

### CODE REVIEW

**Comment by simpl** [comment]
Thank you for your pull request, but it's not a typo.

bucket is a pointer to an array of pointers to ngx_str_t's, and is defined as:

ngx_str_t  **bucket

at the top of the function (line 64).

Furthermore, in that function you can see that there a loop over all the bucket pointers (lines 173-176), with the pointer deferencing.

While sizeof (ngx_str_t *) and sizeof (ngx_str_t **) are technically the same, it would be a semantic error to not include both pointers in the definition.

Thanks again.

**Comment by zhuizhuhaomeng** [comment]
we need to alloc space for buckets elements whose size is sizeof(ngx_str_t *).
so we should use bucket = ngx_palloc (cf->pool, buckets * sizeof (ngx_str_t *))

if you use sizeof (ngx_str_t **) which means the element type is ngx_str_t **, and the container type shoube  ngx_str_t ***.

**Comment by simpl** [comment]
Yes, I see.  Well spotted.  Thanks.

**Comment by zhuizhuhaomeng** [comment]
@simpl  Would you please create a new tag?

**Comment by simpl** [comment]
@zhuizhuhaomeng Done - v0.3.2.

**Pull request merged**
